### ISSUE TITLE
How to mock a call-activity?

### ISSUE THREAD

**Issue by RasPelikan** [camunda-community-hub/camunda-platform-scenario#14]
I use camunda-bpm-assert-scenario in combination with camunda-bpmn-process-test-coverage. I built a test covering all nodes but the overall coverage is still not 100%. My process includes a call-activity which runs using a default scenario. For this reason the call-activity's coverage is not 100% (in fact 87.1%) and this coverage affects the overall coverage of the parent process. Since the call-activity's process got its own test I do not force the parent's process test to gain 100% coverage of the call-activity's process.

Could you add something like

`when(parentScenario.runsCallActivity("CallActivity")).thenReturn(`
`Scenario.mock((callActivity) -> callActivity.complete(withVariables("A", Boolean.TRUE)));`

to mock entire call-activities?

If a missed anything I appreciate every hint.

Regards

**Comment by martinschimak** [comment]
Hi @RasPelikan - my current thoughts are the following: 

1) your discussion of the process test coverage also points in the direction of a feature for that library... whether to include (a specific or all call activities) in the overall coverage ratio calculation or not...

2) "mocking" call activities can actually be simulated by deploying a simple process with an appropriate key... this can also be done on the fly by using the model api. This process could then also directly "complete" with a state holding certain variables.

3) Having said that I think that this could become a feature for "scenario", but I want to let it "sink in" a bit longer in order to understand whether it is a good idea to have that as a scenario feature... and if yes in which exact form.

@berndruecker Do I remember correctly that you also wanted to have that? Do you have any more current thoughts regarding this? Any thoughts appreciated! And thanks for this proposal @RasPelikan !

Martin.

**Comment by berndruecker** [comment]
I think it would be very helpful to have a possibility to easily mock a called element (BPMN or CMMN). Having the possibility to assert/define variables in that called element would make sense in my oppinion.

**Comment by kjonnala** [comment]
Hi, 
  We are running into a similar problem and are using Camunda version 7.8. Is this doable in that version ?

**Comment by cray935** [comment]
Is this project still active? I'd like to see that feature, too.
